/**
 * Curated seed list of popular ATS slugs across providers.
 * Users can add more from the Sources UI.
 */
export const SEED_SLUGS: Array<{ provider: string; slug: string; display: string }> = [
  // ============================================================
  // Greenhouse (~120) — big tech, fintech, AI, climate, devtools
  // ============================================================
  { provider: 'greenhouse', slug: 'airbnb', display: 'Airbnb' },
  { provider: 'greenhouse', slug: 'stripe', display: 'Stripe' },
  { provider: 'greenhouse', slug: 'discord', display: 'Discord' },
  { provider: 'greenhouse', slug: 'figma', display: 'Figma' },
  { provider: 'greenhouse', slug: 'reddit', display: 'Reddit' },
  { provider: 'greenhouse', slug: 'doordash', display: 'DoorDash' },
  { provider: 'greenhouse', slug: 'instacart', display: 'Instacart' },
  { provider: 'greenhouse', slug: 'coinbase', display: 'Coinbase' },
  { provider: 'greenhouse', slug: 'roblox', display: 'Roblox' },
  { provider: 'greenhouse', slug: 'pinterest', display: 'Pinterest' },
  { provider: 'greenhouse', slug: 'robinhood', display: 'Robinhood' },
  { provider: 'greenhouse', slug: 'plaid', display: 'Plaid' },
  { provider: 'greenhouse', slug: 'cloudflare', display: 'Cloudflare' },
  { provider: 'greenhouse', slug: 'gitlab', display: 'GitLab' },
  { provider: 'greenhouse', slug: 'asana', display: 'Asana' },
  { provider: 'greenhouse', slug: 'datadog', display: 'Datadog' },
  { provider: 'greenhouse', slug: 'mongodb', display: 'MongoDB' },
  { provider: 'greenhouse', slug: 'duolingo', display: 'Duolingo' },
  { provider: 'greenhouse', slug: 'samsara', display: 'Samsara' },
  { provider: 'greenhouse', slug: 'rippling', display: 'Rippling' },
  { provider: 'greenhouse', slug: 'brex', display: 'Brex' },
  { provider: 'greenhouse', slug: 'ramp', display: 'Ramp' },
  { provider: 'greenhouse', slug: 'mercury', display: 'Mercury' },
  { provider: 'greenhouse', slug: 'retool', display: 'Retool' },
  { provider: 'greenhouse', slug: 'webflow', display: 'Webflow' },
  { provider: 'greenhouse', slug: 'notion', display: 'Notion' },
  { provider: 'greenhouse', slug: 'snowflake', display: 'Snowflake' },
  { provider: 'greenhouse', slug: 'databricks', display: 'Databricks' },
  { provider: 'greenhouse', slug: 'twilio', display: 'Twilio' },
  { provider: 'greenhouse', slug: 'square', display: 'Block / Square' },
  { provider: 'greenhouse', slug: 'dropbox', display: 'Dropbox' },
  { provider: 'greenhouse', slug: 'lyft', display: 'Lyft' },
  { provider: 'greenhouse', slug: 'pagerduty', display: 'PagerDuty' },
  { provider: 'greenhouse', slug: 'okta', display: 'Okta' },
  { provider: 'greenhouse', slug: 'segment', display: 'Segment' },
  { provider: 'greenhouse', slug: 'fivetran', display: 'Fivetran' },
  { provider: 'greenhouse', slug: 'dbtlabsinc', display: 'dbt Labs' },
  { provider: 'greenhouse', slug: 'getclay', display: 'Clay' },
  { provider: 'greenhouse', slug: 'gusto', display: 'Gusto' },
  { provider: 'greenhouse', slug: 'zendesk', display: 'Zendesk' },
  { provider: 'greenhouse', slug: 'hashicorp', display: 'HashiCorp' },
  { provider: 'greenhouse', slug: 'elastic', display: 'Elastic' },
  { provider: 'greenhouse', slug: 'confluent', display: 'Confluent' },
  { provider: 'greenhouse', slug: 'circleci', display: 'CircleCI' },
  { provider: 'greenhouse', slug: 'launchdarkly', display: 'LaunchDarkly' },
  { provider: 'greenhouse', slug: 'flexport', display: 'Flexport' },
  { provider: 'greenhouse', slug: 'chime', display: 'Chime' },
  { provider: 'greenhouse', slug: 'affirm', display: 'Affirm' },
  { provider: 'greenhouse', slug: 'klarna', display: 'Klarna' },
  { provider: 'greenhouse', slug: 'wise', display: 'Wise' },
  { provider: 'greenhouse', slug: 'sofi', display: 'SoFi' },
  { provider: 'greenhouse', slug: 'block', display: 'Block' },
  { provider: 'greenhouse', slug: 'gemini', display: 'Gemini (Crypto)' },
  { provider: 'greenhouse', slug: 'opensea', display: 'OpenSea' },
  { provider: 'greenhouse', slug: 'chainalysis', display: 'Chainalysis' },
  { provider: 'greenhouse', slug: 'consensys', display: 'ConsenSys' },
  { provider: 'greenhouse', slug: 'crusoeenergysystems', display: 'Crusoe' },
  { provider: 'greenhouse', slug: 'tesla', display: 'Tesla' },
  { provider: 'greenhouse', slug: 'rivian', display: 'Rivian' },
  { provider: 'greenhouse', slug: 'lucidmotors', display: 'Lucid Motors' },
  { provider: 'greenhouse', slug: 'sentry', display: 'Sentry' },
  { provider: 'greenhouse', slug: 'temporaltechnologies', display: 'Temporal' },
  { provider: 'greenhouse', slug: 'sourcegraph', display: 'Sourcegraph' },
  { provider: 'greenhouse', slug: 'wandb', display: 'Weights & Biases' },
  { provider: 'greenhouse', slug: 'replit', display: 'Replit' },
  { provider: 'greenhouse', slug: 'vercel', display: 'Vercel' },
  { provider: 'greenhouse', slug: 'netlify', display: 'Netlify' },
  { provider: 'greenhouse', slug: 'render', display: 'Render' },
  { provider: 'greenhouse', slug: 'fly', display: 'Fly.io' },
  { provider: 'greenhouse', slug: 'pulumi', display: 'Pulumi' },
  { provider: 'greenhouse', slug: 'tailscale', display: 'Tailscale' },
  { provider: 'greenhouse', slug: 'planetscale', display: 'PlanetScale' },
  { provider: 'greenhouse', slug: 'cockroachlabs', display: 'CockroachDB' },
  { provider: 'greenhouse', slug: 'singlestore', display: 'SingleStore' },
  { provider: 'greenhouse', slug: 'starburst', display: 'Starburst' },
  { provider: 'greenhouse', slug: 'imply', display: 'Imply' },
  { provider: 'greenhouse', slug: 'grafanalabs', display: 'Grafana Labs' },
  { provider: 'greenhouse', slug: 'newrelic', display: 'New Relic' },
  { provider: 'greenhouse', slug: 'lightstep', display: 'Lightstep' },
  { provider: 'greenhouse', slug: 'honeycomb', display: 'Honeycomb' },
  { provider: 'greenhouse', slug: 'logz', display: 'Logz.io' },
  { provider: 'greenhouse', slug: 'splunk', display: 'Splunk' },
  { provider: 'greenhouse', slug: 'snyk', display: 'Snyk' },
  { provider: 'greenhouse', slug: 'crowdstrike', display: 'CrowdStrike' },
  { provider: 'greenhouse', slug: 'sentinelone', display: 'SentinelOne' },
  { provider: 'greenhouse', slug: 'cloudbees', display: 'CloudBees' },
  { provider: 'greenhouse', slug: 'jfrog', display: 'JFrog' },
  { provider: 'greenhouse', slug: 'puppet', display: 'Puppet' },
  { provider: 'greenhouse', slug: 'chef', display: 'Chef' },
  { provider: 'greenhouse', slug: 'mulesoft', display: 'MuleSoft' },
  { provider: 'greenhouse', slug: 'salesforce', display: 'Salesforce' },
  { provider: 'greenhouse', slug: 'box', display: 'Box' },
  { provider: 'greenhouse', slug: 'docker', display: 'Docker' },
  { provider: 'greenhouse', slug: 'postman', display: 'Postman' },
  { provider: 'greenhouse', slug: 'mux', display: 'Mux' },
  { provider: 'greenhouse', slug: 'algolia', display: 'Algolia' },
  { provider: 'greenhouse', slug: 'contentful', display: 'Contentful' },
  { provider: 'greenhouse', slug: 'sanity', display: 'Sanity' },
  { provider: 'greenhouse', slug: 'shogun', display: 'Shogun' },
  { provider: 'greenhouse', slug: 'amplitude', display: 'Amplitude' },
  { provider: 'greenhouse', slug: 'mixpanel', display: 'Mixpanel' },
  { provider: 'greenhouse', slug: 'heap', display: 'Heap' },
  { provider: 'greenhouse', slug: 'fullstory', display: 'FullStory' },
  { provider: 'greenhouse', slug: 'iterable', display: 'Iterable' },
  { provider: 'greenhouse', slug: 'sendgrid', display: 'SendGrid' },
  { provider: 'greenhouse', slug: 'mailchimp', display: 'Mailchimp' },
  { provider: 'greenhouse', slug: 'klaviyo', display: 'Klaviyo' },
  { provider: 'greenhouse', slug: 'hubspot', display: 'HubSpot' },
  { provider: 'greenhouse', slug: 'zoom', display: 'Zoom' },
  { provider: 'greenhouse', slug: 'slack', display: 'Slack' },
  { provider: 'greenhouse', slug: 'miro', display: 'Miro' },
  { provider: 'greenhouse', slug: 'loom', display: 'Loom' },
  { provider: 'greenhouse', slug: 'descript', display: 'Descript' },
  { provider: 'greenhouse', slug: 'canva', display: 'Canva' },
  { provider: 'greenhouse', slug: 'grammarly', display: 'Grammarly' },
  { provider: 'greenhouse', slug: 'glean', display: 'Glean' },
  { provider: 'greenhouse', slug: 'character', display: 'Character.AI' },
  { provider: 'greenhouse', slug: 'scaleai', display: 'Scale AI' },
  { provider: 'greenhouse', slug: 'runwayml', display: 'Runway' },
  { provider: 'greenhouse', slug: 'midjourney', display: 'Midjourney' },
  { provider: 'greenhouse', slug: 'cohere', display: 'Cohere' },
  { provider: 'greenhouse', slug: 'adept', display: 'Adept' },
  { provider: 'greenhouse', slug: 'inflectionai', display: 'Inflection AI' },
  { provider: 'greenhouse', slug: 'imbue', display: 'Imbue' },

  // ============================================================
  // Lever (~50)
  // ============================================================
  { provider: 'lever', slug: 'netflix', display: 'Netflix' },
  { provider: 'lever', slug: 'spotify', display: 'Spotify' },
  { provider: 'lever', slug: 'shopify', display: 'Shopify' },
  { provider: 'lever', slug: 'palantir', display: 'Palantir' },
  { provider: 'lever', slug: 'mistral', display: 'Mistral AI' },
  { provider: 'lever', slug: 'anthropic', display: 'Anthropic' },
  { provider: 'lever', slug: 'eventbrite', display: 'Eventbrite' },
  { provider: 'lever', slug: 'attentive', display: 'Attentive' },
  { provider: 'lever', slug: 'matterport', display: 'Matterport' },
  { provider: 'lever', slug: 'kraken', display: 'Kraken' },
  { provider: 'lever', slug: 'block', display: 'Block (Lever)' },
  { provider: 'lever', slug: 'mux', display: 'Mux (Lever)' },
  { provider: 'lever', slug: 'angellist', display: 'AngelList' },
  { provider: 'lever', slug: 'benchling', display: 'Benchling' },
  { provider: 'lever', slug: 'rapid7', display: 'Rapid7' },
  { provider: 'lever', slug: 'pendo', display: 'Pendo' },
  { provider: 'lever', slug: 'figure', display: 'Figure' },
  { provider: 'lever', slug: 'ironclad', display: 'Ironclad' },
  { provider: 'lever', slug: 'flexcompute', display: 'Flexcompute' },
  { provider: 'lever', slug: 'opendoor', display: 'Opendoor' },
  { provider: 'lever', slug: 'zwift', display: 'Zwift' },
  { provider: 'lever', slug: 'mythical', display: 'Mythical Games' },
  { provider: 'lever', slug: 'truework', display: 'Truework' },
  { provider: 'lever', slug: 'oscar', display: 'Oscar Health' },
  { provider: 'lever', slug: 'getmaple', display: 'Maple' },
  { provider: 'lever', slug: 'thirdlove', display: 'ThirdLove' },
  { provider: 'lever', slug: 'lattice', display: 'Lattice' },
  { provider: 'lever', slug: 'pilot', display: 'Pilot' },
  { provider: 'lever', slug: 'frame', display: 'Frame.io' },
  { provider: 'lever', slug: 'gong', display: 'Gong' },
  { provider: 'lever', slug: 'kong', display: 'Kong' },
  { provider: 'lever', slug: 'pleo', display: 'Pleo' },
  { provider: 'lever', slug: 'remote', display: 'Remote' },
  { provider: 'lever', slug: 'deel', display: 'Deel' },
  { provider: 'lever', slug: 'kandji', display: 'Kandji' },
  { provider: 'lever', slug: 'modernhealth', display: 'Modern Health' },
  { provider: 'lever', slug: 'patreon', display: 'Patreon' },
  { provider: 'lever', slug: 'gocardless', display: 'GoCardless' },
  { provider: 'lever', slug: 'workato', display: 'Workato' },
  { provider: 'lever', slug: 'tubi', display: 'Tubi' },

  // ============================================================
  // Ashby (~40) — AI labs & devtools
  // ============================================================
  { provider: 'ashby', slug: 'openai', display: 'OpenAI' },
  { provider: 'ashby', slug: 'linear', display: 'Linear' },
  { provider: 'ashby', slug: 'ramp', display: 'Ramp (Ashby)' },
  { provider: 'ashby', slug: 'vercel', display: 'Vercel (Ashby)' },
  { provider: 'ashby', slug: 'replicate', display: 'Replicate' },
  { provider: 'ashby', slug: 'posthog', display: 'PostHog' },
  { provider: 'ashby', slug: 'supabase', display: 'Supabase' },
  { provider: 'ashby', slug: 'huggingface', display: 'Hugging Face' },
  { provider: 'ashby', slug: 'browserbase', display: 'Browserbase' },
  { provider: 'ashby', slug: 'cursor', display: 'Cursor' },
  { provider: 'ashby', slug: 'perplexity', display: 'Perplexity' },
  { provider: 'ashby', slug: 'elevenlabs', display: 'ElevenLabs' },
  { provider: 'ashby', slug: 'thoughtspot', display: 'ThoughtSpot' },
  { provider: 'ashby', slug: 'cresta', display: 'Cresta' },
  { provider: 'ashby', slug: 'mercor', display: 'Mercor' },
  { provider: 'ashby', slug: 'harvey', display: 'Harvey' },
  { provider: 'ashby', slug: 'decagon', display: 'Decagon' },
  { provider: 'ashby', slug: 'sierra', display: 'Sierra' },
  { provider: 'ashby', slug: 'sakana', display: 'Sakana AI' },
  { provider: 'ashby', slug: 'crusoe', display: 'Crusoe (Ashby)' },
  { provider: 'ashby', slug: 'magicschool', display: 'MagicSchool' },
  { provider: 'ashby', slug: 'speak', display: 'Speak' },
  { provider: 'ashby', slug: 'modal', display: 'Modal' },
  { provider: 'ashby', slug: 'foundry', display: 'Foundry' },
  { provider: 'ashby', slug: 'together', display: 'Together AI' },
  { provider: 'ashby', slug: 'lambdalabs', display: 'Lambda Labs' },
  { provider: 'ashby', slug: 'codeium', display: 'Codeium' },
  { provider: 'ashby', slug: 'tabnine', display: 'Tabnine' },
  { provider: 'ashby', slug: 'phantom', display: 'Phantom' },
  { provider: 'ashby', slug: 'arc', display: 'Arc / The Browser Company' },
  { provider: 'ashby', slug: 'raycast', display: 'Raycast' },
  { provider: 'ashby', slug: 'warp', display: 'Warp' },
  { provider: 'ashby', slug: 'screenshot', display: 'Screenshot.so' },
  { provider: 'ashby', slug: 'tessl', display: 'Tessl' },
  { provider: 'ashby', slug: 'arcade', display: 'Arcade' },
  { provider: 'ashby', slug: 'tldraw', display: 'tldraw' },

  // ============================================================
  // Workable (~20)
  // ============================================================
  { provider: 'workable', slug: 'doist', display: 'Doist' },
  { provider: 'workable', slug: 'invisionapp', display: 'InVision' },
  { provider: 'workable', slug: 'andela', display: 'Andela' },
  { provider: 'workable', slug: 'remotebase', display: 'RemoteBase' },
  { provider: 'workable', slug: 'omnipresent', display: 'Omnipresent' },
  { provider: 'workable', slug: 'aircall', display: 'Aircall' },
  { provider: 'workable', slug: 'mira', display: 'Mira' },
  { provider: 'workable', slug: 'volotea', display: 'Volotea' },
  { provider: 'workable', slug: 'kpler', display: 'Kpler' },
  { provider: 'workable', slug: 'multiplier', display: 'Multiplier' },

  // ============================================================
  // SmartRecruiters (~12)
  // ============================================================
  { provider: 'smartrecruiters', slug: 'Bosch', display: 'Bosch' },
  { provider: 'smartrecruiters', slug: 'Visa', display: 'Visa' },
  { provider: 'smartrecruiters', slug: 'Square', display: 'Square (SR)' },
  { provider: 'smartrecruiters', slug: 'Ubisoft', display: 'Ubisoft' },
  { provider: 'smartrecruiters', slug: 'IKEA', display: 'IKEA' },
  { provider: 'smartrecruiters', slug: 'Skyscanner', display: 'Skyscanner' },
  { provider: 'smartrecruiters', slug: 'Equinix', display: 'Equinix' },
  { provider: 'smartrecruiters', slug: 'McDonalds1', display: 'McDonald\'s' },

  // ============================================================
  // Recruitee (~5)
  // ============================================================
  { provider: 'recruitee', slug: 'recruitee', display: 'Recruitee' },
  { provider: 'recruitee', slug: 'kpn', display: 'KPN' },
  { provider: 'recruitee', slug: 'channable', display: 'Channable' },

  // ============================================================
  // Teamtailor (~15)
  // ============================================================
  { provider: 'teamtailor', slug: 'voi', display: 'Voi' },
  { provider: 'teamtailor', slug: 'tink', display: 'Tink' },
  { provider: 'teamtailor', slug: 'epidemicsound', display: 'Epidemic Sound' },
  { provider: 'teamtailor', slug: 'klarna-careers', display: 'Klarna Careers' },
  { provider: 'teamtailor', slug: 'kry', display: 'Kry / Livi' },
  { provider: 'teamtailor', slug: 'mentimeter', display: 'Mentimeter' },
  { provider: 'teamtailor', slug: 'budbee', display: 'Budbee' },
  { provider: 'teamtailor', slug: 'lendo', display: 'Lendo' },
  { provider: 'teamtailor', slug: 'einride', display: 'Einride' },
  { provider: 'teamtailor', slug: 'qliro', display: 'Qliro' },

  // ============================================================
  // Personio (~8) — German/EU mid-market
  // ============================================================
  { provider: 'personio', slug: 'personio', display: 'Personio' },
  { provider: 'personio', slug: 'getsafe', display: 'Getsafe' },
  { provider: 'personio', slug: 'choco', display: 'Choco' },
  { provider: 'personio', slug: 'gorgias', display: 'Gorgias' },
  { provider: 'personio', slug: 'wefox', display: 'wefox' },

  // ============================================================
  // BambooHR (~5)
  // ============================================================
  { provider: 'bamboohr', slug: 'bamboohr', display: 'BambooHR' },
  { provider: 'bamboohr', slug: 'fivestars', display: 'Fivestars' },
];
