/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminObservabilityRouteImport } from './routes/admin/observability'
import { Route as AdminFlagsRouteImport } from './routes/admin/flags'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AuthenticatedWorkerRouteImport } from './routes/_authenticated/worker'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedFiltersRouteImport } from './routes/_authenticated/filters'
import { Route as AuthenticatedExtensionRouteImport } from './routes/_authenticated/extension'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoverLettersRouteImport } from './routes/_authenticated/cover-letters'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedProfileScreeningRouteImport } from './routes/_authenticated/profile.screening'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'
import { Route as ApiPublicWorkerEnvRouteImport } from './routes/api/public/worker.env'
import { Route as ApiPublicSourcesWorkerStatusRouteImport } from './routes/api/public/sources/worker-status'
import { Route as ApiPublicSourcesUploadCookiesRouteImport } from './routes/api/public/sources/upload-cookies'
import { Route as ApiPublicSourcesRunTierRouteImport } from './routes/api/public/sources/run-tier'
import { Route as ApiPublicSourcesQueueApplyRouteImport } from './routes/api/public/sources/queue-apply'
import { Route as ApiPublicSourcesIngestExtensionRouteImport } from './routes/api/public/sources/ingest-extension'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'
import { Route as ApiPublicHooksCheckHeartbeatRouteImport } from './routes/api/public/hooks/check-heartbeat'
import { Route as ApiPublicHooksApplyWorkerRouteImport } from './routes/api/public/hooks/apply-worker'
import { Route as ApiPublicExtensionErrorReportRouteImport } from './routes/api/public/extension/error-report'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWorkerRoute = AuthenticatedWorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiltersRoute = AuthenticatedFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExtensionRoute = AuthenticatedExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoverLettersRoute =
  AuthenticatedCoverLettersRouteImport.update({
    id: '/cover-letters',
    path: '/cover-letters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileScreeningRoute =
  AuthenticatedProfileScreeningRouteImport.update({
    id: '/screening',
    path: '/screening',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiPublicWorkerEnvRoute = ApiPublicWorkerEnvRouteImport.update({
  id: '/api/public/worker/env',
  path: '/api/public/worker/env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSourcesWorkerStatusRoute =
  ApiPublicSourcesWorkerStatusRouteImport.update({
    id: '/api/public/sources/worker-status',
    path: '/api/public/sources/worker-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSourcesUploadCookiesRoute =
  ApiPublicSourcesUploadCookiesRouteImport.update({
    id: '/api/public/sources/upload-cookies',
    path: '/api/public/sources/upload-cookies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSourcesRunTierRoute = ApiPublicSourcesRunTierRouteImport.update({
  id: '/api/public/sources/run-tier',
  path: '/api/public/sources/run-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSourcesQueueApplyRoute =
  ApiPublicSourcesQueueApplyRouteImport.update({
    id: '/api/public/sources/queue-apply',
    path: '/api/public/sources/queue-apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSourcesIngestExtensionRoute =
  ApiPublicSourcesIngestExtensionRouteImport.update({
    id: '/api/public/sources/ingest-extension',
    path: '/api/public/sources/ingest-extension',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckHeartbeatRoute =
  ApiPublicHooksCheckHeartbeatRouteImport.update({
    id: '/api/public/hooks/check-heartbeat',
    path: '/api/public/hooks/check-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApplyWorkerRoute =
  ApiPublicHooksApplyWorkerRouteImport.update({
    id: '/api/public/hooks/apply-worker',
    path: '/api/public/hooks/apply-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionErrorReportRoute =
  ApiPublicExtensionErrorReportRouteImport.update({
    id: '/api/public/extension/error-report',
    path: '/api/public/extension/error-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/automation': typeof AuthenticatedAutomationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/filters': typeof AuthenticatedFiltersRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/resume': typeof AuthenticatedResumeRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/': typeof AdminIndexRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/profile/screening': typeof AuthenticatedProfileScreeningRoute
  '/api/public/extension/error-report': typeof ApiPublicExtensionErrorReportRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/ingest-extension': typeof ApiPublicSourcesIngestExtensionRoute
  '/api/public/sources/queue-apply': typeof ApiPublicSourcesQueueApplyRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
  '/api/public/sources/upload-cookies': typeof ApiPublicSourcesUploadCookiesRoute
  '/api/public/sources/worker-status': typeof ApiPublicSourcesWorkerStatusRoute
  '/api/public/worker/env': typeof ApiPublicWorkerEnvRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/automation': typeof AuthenticatedAutomationRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/filters': typeof AuthenticatedFiltersRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/resume': typeof AuthenticatedResumeRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/worker': typeof AuthenticatedWorkerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin': typeof AdminIndexRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/profile/screening': typeof AuthenticatedProfileScreeningRoute
  '/api/public/extension/error-report': typeof ApiPublicExtensionErrorReportRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/ingest-extension': typeof ApiPublicSourcesIngestExtensionRoute
  '/api/public/sources/queue-apply': typeof ApiPublicSourcesQueueApplyRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
  '/api/public/sources/upload-cookies': typeof ApiPublicSourcesUploadCookiesRoute
  '/api/public/sources/worker-status': typeof ApiPublicSourcesWorkerStatusRoute
  '/api/public/worker/env': typeof ApiPublicWorkerEnvRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cover-letters': typeof AuthenticatedCoverLettersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extension': typeof AuthenticatedExtensionRoute
  '/_authenticated/filters': typeof AuthenticatedFiltersRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/worker': typeof AuthenticatedWorkerRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/profile/screening': typeof AuthenticatedProfileScreeningRoute
  '/api/public/extension/error-report': typeof ApiPublicExtensionErrorReportRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/ingest-extension': typeof ApiPublicSourcesIngestExtensionRoute
  '/api/public/sources/queue-apply': typeof ApiPublicSourcesQueueApplyRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
  '/api/public/sources/upload-cookies': typeof ApiPublicSourcesUploadCookiesRoute
  '/api/public/sources/worker-status': typeof ApiPublicSourcesWorkerStatusRoute
  '/api/public/worker/env': typeof ApiPublicWorkerEnvRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/automation'
    | '/billing'
    | '/cover-letters'
    | '/dashboard'
    | '/extension'
    | '/filters'
    | '/jobs'
    | '/logs'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/setup'
    | '/sources'
    | '/worker'
    | '/admin/audit'
    | '/admin/flags'
    | '/admin/observability'
    | '/admin/plans'
    | '/admin/system'
    | '/admin/'
    | '/applications/$id'
    | '/profile/screening'
    | '/api/public/extension/error-report'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/ingest-extension'
    | '/api/public/sources/queue-apply'
    | '/api/public/sources/run-tier'
    | '/api/public/sources/upload-cookies'
    | '/api/public/sources/worker-status'
    | '/api/public/worker/env'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/automation'
    | '/billing'
    | '/cover-letters'
    | '/dashboard'
    | '/extension'
    | '/filters'
    | '/jobs'
    | '/logs'
    | '/notifications'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/resume'
    | '/setup'
    | '/sources'
    | '/worker'
    | '/admin/audit'
    | '/admin/flags'
    | '/admin/observability'
    | '/admin/plans'
    | '/admin/system'
    | '/admin'
    | '/applications/$id'
    | '/profile/screening'
    | '/api/public/extension/error-report'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/ingest-extension'
    | '/api/public/sources/queue-apply'
    | '/api/public/sources/run-tier'
    | '/api/public/sources/upload-cookies'
    | '/api/public/sources/worker-status'
    | '/api/public/worker/env'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/admin-login'
    | '/login'
    | '/reset-password'
    | '/_authenticated/applications'
    | '/_authenticated/automation'
    | '/_authenticated/billing'
    | '/_authenticated/cover-letters'
    | '/_authenticated/dashboard'
    | '/_authenticated/extension'
    | '/_authenticated/filters'
    | '/_authenticated/jobs'
    | '/_authenticated/logs'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/privacy'
    | '/_authenticated/profile'
    | '/_authenticated/resume'
    | '/_authenticated/setup'
    | '/_authenticated/sources'
    | '/_authenticated/worker'
    | '/admin/audit'
    | '/admin/flags'
    | '/admin/observability'
    | '/admin/plans'
    | '/admin/system'
    | '/admin/'
    | '/_authenticated/applications/$id'
    | '/_authenticated/profile/screening'
    | '/api/public/extension/error-report'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/ingest-extension'
    | '/api/public/sources/queue-apply'
    | '/api/public/sources/run-tier'
    | '/api/public/sources/upload-cookies'
    | '/api/public/sources/worker-status'
    | '/api/public/worker/env'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicExtensionErrorReportRoute: typeof ApiPublicExtensionErrorReportRoute
  ApiPublicHooksApplyWorkerRoute: typeof ApiPublicHooksApplyWorkerRoute
  ApiPublicHooksCheckHeartbeatRoute: typeof ApiPublicHooksCheckHeartbeatRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
  ApiPublicSourcesIngestExtensionRoute: typeof ApiPublicSourcesIngestExtensionRoute
  ApiPublicSourcesQueueApplyRoute: typeof ApiPublicSourcesQueueApplyRoute
  ApiPublicSourcesRunTierRoute: typeof ApiPublicSourcesRunTierRoute
  ApiPublicSourcesUploadCookiesRoute: typeof ApiPublicSourcesUploadCookiesRoute
  ApiPublicSourcesWorkerStatusRoute: typeof ApiPublicSourcesWorkerStatusRoute
  ApiPublicWorkerEnvRoute: typeof ApiPublicWorkerEnvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/observability': {
      id: '/admin/observability'
      path: '/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/worker': {
      id: '/_authenticated/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof AuthenticatedWorkerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filters': {
      id: '/_authenticated/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof AuthenticatedFiltersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extension': {
      id: '/_authenticated/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof AuthenticatedExtensionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cover-letters': {
      id: '/_authenticated/cover-letters'
      path: '/cover-letters'
      fullPath: '/cover-letters'
      preLoaderRoute: typeof AuthenticatedCoverLettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/screening': {
      id: '/_authenticated/profile/screening'
      path: '/screening'
      fullPath: '/profile/screening'
      preLoaderRoute: typeof AuthenticatedProfileScreeningRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/public/worker/env': {
      id: '/api/public/worker/env'
      path: '/api/public/worker/env'
      fullPath: '/api/public/worker/env'
      preLoaderRoute: typeof ApiPublicWorkerEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sources/worker-status': {
      id: '/api/public/sources/worker-status'
      path: '/api/public/sources/worker-status'
      fullPath: '/api/public/sources/worker-status'
      preLoaderRoute: typeof ApiPublicSourcesWorkerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sources/upload-cookies': {
      id: '/api/public/sources/upload-cookies'
      path: '/api/public/sources/upload-cookies'
      fullPath: '/api/public/sources/upload-cookies'
      preLoaderRoute: typeof ApiPublicSourcesUploadCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sources/run-tier': {
      id: '/api/public/sources/run-tier'
      path: '/api/public/sources/run-tier'
      fullPath: '/api/public/sources/run-tier'
      preLoaderRoute: typeof ApiPublicSourcesRunTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sources/queue-apply': {
      id: '/api/public/sources/queue-apply'
      path: '/api/public/sources/queue-apply'
      fullPath: '/api/public/sources/queue-apply'
      preLoaderRoute: typeof ApiPublicSourcesQueueApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sources/ingest-extension': {
      id: '/api/public/sources/ingest-extension'
      path: '/api/public/sources/ingest-extension'
      fullPath: '/api/public/sources/ingest-extension'
      preLoaderRoute: typeof ApiPublicSourcesIngestExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-heartbeat': {
      id: '/api/public/hooks/check-heartbeat'
      path: '/api/public/hooks/check-heartbeat'
      fullPath: '/api/public/hooks/check-heartbeat'
      preLoaderRoute: typeof ApiPublicHooksCheckHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apply-worker': {
      id: '/api/public/hooks/apply-worker'
      path: '/api/public/hooks/apply-worker'
      fullPath: '/api/public/hooks/apply-worker'
      preLoaderRoute: typeof ApiPublicHooksApplyWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/error-report': {
      id: '/api/public/extension/error-report'
      path: '/api/public/extension/error-report'
      fullPath: '/api/public/extension/error-report'
      preLoaderRoute: typeof ApiPublicExtensionErrorReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileScreeningRoute: typeof AuthenticatedProfileScreeningRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileScreeningRoute: AuthenticatedProfileScreeningRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCoverLettersRoute: typeof AuthenticatedCoverLettersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtensionRoute: typeof AuthenticatedExtensionRoute
  AuthenticatedFiltersRoute: typeof AuthenticatedFiltersRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedWorkerRoute: typeof AuthenticatedWorkerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCoverLettersRoute: AuthenticatedCoverLettersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtensionRoute: AuthenticatedExtensionRoute,
  AuthenticatedFiltersRoute: AuthenticatedFiltersRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedWorkerRoute: AuthenticatedWorkerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicExtensionErrorReportRoute: ApiPublicExtensionErrorReportRoute,
  ApiPublicHooksApplyWorkerRoute: ApiPublicHooksApplyWorkerRoute,
  ApiPublicHooksCheckHeartbeatRoute: ApiPublicHooksCheckHeartbeatRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
  ApiPublicSourcesIngestExtensionRoute: ApiPublicSourcesIngestExtensionRoute,
  ApiPublicSourcesQueueApplyRoute: ApiPublicSourcesQueueApplyRoute,
  ApiPublicSourcesRunTierRoute: ApiPublicSourcesRunTierRoute,
  ApiPublicSourcesUploadCookiesRoute: ApiPublicSourcesUploadCookiesRoute,
  ApiPublicSourcesWorkerStatusRoute: ApiPublicSourcesWorkerStatusRoute,
  ApiPublicWorkerEnvRoute: ApiPublicWorkerEnvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
