/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedFiltersRouteImport } from './routes/_authenticated/filters'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'
import { Route as ApiPublicSourcesRunTierRouteImport } from './routes/api/public/sources/run-tier'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'
import { Route as ApiPublicHooksCheckHeartbeatRouteImport } from './routes/api/public/hooks/check-heartbeat'
import { Route as ApiPublicHooksApplyWorkerRouteImport } from './routes/api/public/hooks/apply-worker'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFiltersRoute = AuthenticatedFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const ApiPublicSourcesRunTierRoute = ApiPublicSourcesRunTierRouteImport.update({
  id: '/api/public/sources/run-tier',
  path: '/api/public/sources/run-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckHeartbeatRoute =
  ApiPublicHooksCheckHeartbeatRouteImport.update({
    id: '/api/public/hooks/check-heartbeat',
    path: '/api/public/hooks/check-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApplyWorkerRoute =
  ApiPublicHooksApplyWorkerRouteImport.update({
    id: '/api/public/hooks/apply-worker',
    path: '/api/public/hooks/apply-worker',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filters': typeof AuthenticatedFiltersRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/automation': typeof AuthenticatedAutomationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/filters': typeof AuthenticatedFiltersRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/filters': typeof AuthenticatedFiltersRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/api/public/hooks/apply-worker': typeof ApiPublicHooksApplyWorkerRoute
  '/api/public/hooks/check-heartbeat': typeof ApiPublicHooksCheckHeartbeatRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/sources/run-tier': typeof ApiPublicSourcesRunTierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/automation'
    | '/dashboard'
    | '/filters'
    | '/jobs'
    | '/logs'
    | '/notifications'
    | '/profile'
    | '/setup'
    | '/sources'
    | '/applications/$id'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/run-tier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/applications'
    | '/automation'
    | '/dashboard'
    | '/filters'
    | '/jobs'
    | '/logs'
    | '/notifications'
    | '/profile'
    | '/setup'
    | '/sources'
    | '/applications/$id'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/run-tier'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/applications'
    | '/_authenticated/automation'
    | '/_authenticated/dashboard'
    | '/_authenticated/filters'
    | '/_authenticated/jobs'
    | '/_authenticated/logs'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/setup'
    | '/_authenticated/sources'
    | '/_authenticated/applications/$id'
    | '/api/public/hooks/apply-worker'
    | '/api/public/hooks/check-heartbeat'
    | '/api/public/hooks/daily-summary'
    | '/api/public/sources/run-tier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksApplyWorkerRoute: typeof ApiPublicHooksApplyWorkerRoute
  ApiPublicHooksCheckHeartbeatRoute: typeof ApiPublicHooksCheckHeartbeatRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
  ApiPublicSourcesRunTierRoute: typeof ApiPublicSourcesRunTierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/filters': {
      id: '/_authenticated/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof AuthenticatedFiltersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/api/public/sources/run-tier': {
      id: '/api/public/sources/run-tier'
      path: '/api/public/sources/run-tier'
      fullPath: '/api/public/sources/run-tier'
      preLoaderRoute: typeof ApiPublicSourcesRunTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-heartbeat': {
      id: '/api/public/hooks/check-heartbeat'
      path: '/api/public/hooks/check-heartbeat'
      fullPath: '/api/public/hooks/check-heartbeat'
      preLoaderRoute: typeof ApiPublicHooksCheckHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/apply-worker': {
      id: '/api/public/hooks/apply-worker'
      path: '/api/public/hooks/apply-worker'
      fullPath: '/api/public/hooks/apply-worker'
      preLoaderRoute: typeof ApiPublicHooksApplyWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFiltersRoute: typeof AuthenticatedFiltersRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFiltersRoute: AuthenticatedFiltersRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksApplyWorkerRoute: ApiPublicHooksApplyWorkerRoute,
  ApiPublicHooksCheckHeartbeatRoute: ApiPublicHooksCheckHeartbeatRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
  ApiPublicSourcesRunTierRoute: ApiPublicSourcesRunTierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
